language: en
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "DucklingHTTPExtractor"
# url of the running duckling server
url: "http://localhost:8000"
# dimensions to extract
# dimensions: ["time"]


# pipeline: 
# # - name: "pretrained_embeddings_spacy"
# - name: "DucklingHTTPExtractor"
# # url of the running duckling server
# url: "http://localhost:8000"
# locale: "NL_Nothing"
# # dimensions to extract
# dimensions: ["time", "number", "amount-of-money", "distance"]
# # allows you to configure the locale, by default the language is